AllCops:
  RunRailsCops: true # always run the rails cops

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 300

Metrics/ClassLength:
  Exclude:
   - 'test/**/*'

Metrics/MethodLength:
  Max: 50

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/DefaultScope:
  Enabled: false

Rails/Output:
  Exclude:
   - 'lib/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
   - 'db/seeds.d/*'

Style/FormatString:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/TrailingUnderscoreVariable:
  Enabled: false

